import React from 'react';
import { Calendar, Clock, Target, CheckSquare, Award } from 'lucide-react';

const StudyPlanViewer = ({ plan }) => {
  if (!plan) return null;

  const data = typeof plan.studyPlan === 'object' ? plan.studyPlan : { summary: plan.studyPlan };
  const dailySchedule = data.dailySchedule || [];
  const examDayTips = data.examDayTips || [];

  return (
    <div className="study-plan-wrapper space-y-6">
      <div className="plan-header-card card p-6 bg-gradient">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <span className="badge badge-accent mb-2">{plan.subject || 'General Subject'}</span>
            <h2 className="text-2xl font-bold text-dark">Personalized Revision Strategy</h2>
            <p className="text-secondary mt-1 max-w-2xl">{data.summary || 'Custom study plan generated by Gemini AI.'}</p>
          </div>
          <div className="plan-meta-grid">
            <div className="meta-pill">
              <Calendar size={18} className="text-primary" />
              <div>
                <div className="text-xs text-muted">Exam Date</div>
                <div className="font-semibold text-sm">{plan.examDate}</div>
              </div>
            </div>
            <div className="meta-pill">
              <Clock size={18} className="text-primary" />
              <div>
                <div className="text-xs text-muted">Daily Goal</div>
                <div className="font-semibold text-sm">{plan.availableTime || '2 Hours'}</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {dailySchedule.length > 0 && (
        <div className="daily-schedule-section">
          <h3 className="section-title text-xl font-bold mb-4 flex items-center">
            <Target size={22} className="text-primary mr-2" /> Daily Roadmap
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {dailySchedule.map((item, idx) => (
              <div key={idx} className="day-card card p-5 hover-shadow">
                <div className="flex justify-between items-start mb-3">
                  <span className="day-badge">{item.day || `Day ${idx + 1}`}</span>
                  {item.focusArea && <span className="text-xs text-primary font-medium">{item.focusArea}</span>}
                </div>
                <h4 className="font-bold text-lg text-dark">{item.topic}</h4>
                {item.tasks && Array.isArray(item.tasks) && (
                  <ul className="task-list mt-3 space-y-2">
                    {item.tasks.map((task, tIdx) => (
                      <li key={tIdx} className="task-item text-sm flex items-start">
                        <CheckSquare size={16} className="text-success mr-2 mt-0.5 flex-shrink-0" />
                        <span>{task}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {examDayTips.length > 0 && (
        <div className="tips-section card p-6 bg-light">
          <h3 className="font-bold text-lg text-dark flex items-center mb-3">
            <Award size={20} className="text-warning mr-2" /> Exam Strategy & Tips
          </h3>
          <ul className="space-y-2">
            {examDayTips.map((tip, idx) => (
              <li key={idx} className="text-sm text-secondary flex items-start">
                <span className="bullet-point text-primary mr-2">•</span>
                <span>{tip}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

export default StudyPlanViewer;
